                                 
    
--Explore all objects in the Database

select * from information_schema.tables

--Explore all coloumns in the Database

select * from information_schema.columns
where table_name = 'dim_customers'
                                

                                -- DIMENSIONS EXPLORATION --

--Explore all countries our customers come from.

select distinct country from [gold.dim_customers]

--Explore all categories "The major Divisions"

select distinct category,subcategory,product_name from [gold.dim_products]
order by 1,2,3


                               -- DATE EXPLORATION --

--find the data of the first and last order
--How many years of sales are available

select
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff (month,min(order_date), max(order_date)) as order_range_months 
from [gold.fact_sales]

--find the youngest and oldest customer
select 
min(birthdate) as oldest_birthdate,
datediff(year, min(birthdate),getdate()) as oldest_age,
max(birthdate) as youngest_birthdate,
datediff(year, max(birthdate), getdate()) as youngest_age
from [gold.dim_customers]
                        

                               -- MEASURES EXPLORATION --
-- Find the Total Sales

select sum(sales_amount) as Total_sales from [gold.fact_sales]

-- Find How many items are Sold

select sum(quantity) as total_quantity from [gold.fact_sales]

-- Find the average selling price

select avg(price) as avg_price from [gold.fact_sales]

-- Find the total number of Orders

select count(order_number) as total_orders from [gold.fact_sales]
select count(distinct order_number) as total_orders from [gold.fact_sales]

-- Find the total number of products

select count(distinct product_key) as total_products from [gold.dim_products]

-- Find the total number of customers

select count(distinct customer_key) as total_customers from [gold.dim_customers]

-- Find the total number of customers that has placed an order

select count(distinct customer_key) as total_customers from [gold.fact_sales]

-- Generate a report that shows all key metrics of the business

select 'Total sales' as measure_name, sum(sales_amount) as measure_value from [gold.fact_sales]
union all
select 'Total quantity' , sum(quantity)  from [gold.fact_sales]
union all
select 'average price', avg(price)  from [gold.fact_sales]
union all
select 'total nr. orders', count(distinct order_number) from [gold.fact_sales]
union all
select 'total nr. products',count(distinct product_key) from [gold.dim_products]
union all
select 'total nr. customers', count(distinct customer_key)  from [gold.dim_customers]
                                      

                                      -- MAGNITUDE ANALYSIS --

-- Find the total customers by countries

select country, count(customer_key) as total_customers from [gold.dim_customers]
group by country
order by total_customers desc

-- Find total customers by gender

select gender, count(customer_key) as total_customers from [gold.dim_customers]
group by gender
order by total_customers desc

-- Find total products by category

select category, count(product_key) as total_products from [gold.dim_products]
group by category
order by total_products desc

-- What is the average costs in each category?

select category,avg(cost) as average_costs from [gold.dim_products]
group by category
order by average_costs desc

-- What is the total revenue generated for each category?


select p.category, sum(f.sales_amount) as total_revenue
from [gold.fact_sales]f
left join [gold.dim_products]p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

-- What is the total revenue generated by each customer?

select c.customer_key,c.first_name,c.last_name, sum(f.sales_amount) as total_revenue
from [gold.fact_sales]f
left join [gold.dim_customers] c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

-- what is the distribution of items sold across countries?


select c.country, sum(f.quantity) as total_sold_items
from [gold.fact_sales]f
left join [gold.dim_customers] c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc


                                          -- RANKING ANALYSIS --

-- Which 5 products generate the highest revenue

select top 5 (p.product_name), sum(f.sales_amount) as total_revenue
from [gold.fact_sales]f
left join [gold.dim_products]p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue desc

-- What are the 5 worst- performing products in terms of sales

select top 5 p.product_name, sum(f.sales_amount) as total_revenue
from [gold.fact_sales]f
left join [gold.dim_products]p
on p.product_key = f.product_key
group by p.product_name
order by  total_revenue asc
